package com.harsh.testingapi.DataClasses

data class Night( val Icon: Int,
                  val IconPhrase: String,
                  val HasPrecipitation: Boolean,
                  val ShortPhrase: String?,
                  val LongPhrase: String?,
                  val PrecipitationProbability: Int,
                  val ThunderstormProbability: Int,
                  val RainProbability: Int,
                  val SnowProbability: Int,
                  val IceProbability: Int,
                  val Wind: Wind?,
                  val WindGust: WindGust?,
                  val TotalLiquid: Measurement?,
                  val Rain: Measurement?,
                  val Snow: Measurement?,
                  val Ice: Measurement?,
                  val HoursOfPrecipitation: Double,
                  val HoursOfRain: Double,
                  val HoursOfSnow: Double,
                  val HoursOfIce: Double,
                  val CloudCover: Int,
                  val Evapotranspiration: Measurement?,
                  val SolarIrradiance: Measurement?,
                  val RelativeHumidity: Humidity?,
                  val WetBulbTemperature: TemperatureDetail?,
                  val WetBulbGlobeTemperature: TemperatureDetail?)
